# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Serandel
tagline:          'Manager by day, Android coder by night'
description:      'Random ramblings, disgressions and the ocassional code snippet found while working with Android. Or playing with it. Whatever.'
url:              http://serandel.github.io
baseurl:          /

author:
  name:           'Sergio Delgado'
  url:            http://es.linkedin.com/pub/sergio-antonio-delgado-quero/15/914/52a/

paginate:         5

# Custom vars
